language: cpp

sudo: required

git:
  depth: false

branches:
  only:
  - master

install:
  - sudo add-apt-repository -y ppa:bartbes/love-stable
  - sudo apt-get -qq update
  - sudo apt-get install -y love
  - git clone -b Toolchain https://github.com/RamiLego4Game/LIKO-12-Disks.git ../Toolchain

before_script:
  - mkdir ../Toolchain/Games
  - cp -v -f *.png ../Toolchain/Games/

script:
  - love ../Toolchain/

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: ../Toolchain/GH-Pages/
